### ISSUE TITLE
groovy script of ultimate encoder fails to load

### ISSUE THREAD

**Issue by H2GamingTW** [GregTechCEu/GregTech-Community-Pack#105]
upon loading into any world the error log pops up
![image](https://github.com/GregTechCEu/GregTech-Community-Pack/assets/86768934/f1336f13-3a4b-4b53-9c98-352e56299b1f)

pack version 1.7.1, 

edit: found out it was the extra ) that was causing the issue.  deleting it fixes the recipe
![scriptErrorSpot](https://github.com/GregTechCEu/GregTech-Community-Pack/assets/86768934/c99b40ab-183a-461c-925d-ac90783c9572)

**Comment by htmlcsjs** [comment]
thats not in the repo wtf
https://github.com/GregTechCEu/GregTech-Community-Pack/blob/28431a8aa765610a0dfc511577545bdddabe0ffe/groovy/postInit/ae2_fc.groovy#L105

**Comment by htmlcsjs** [comment]
now is fixed on cf
