### ISSUE TITLE
Crash report, removing a valve from a (full) multiblock steel tank

### ISSUE THREAD

**Issue by Orzipan** [GregTechCEu/GregTech-Community-Pack#108]
I tried to remove a valve from a (full) multiblock steel tank with my wrench.
[crash-2023-09-28_21.43.37-server.txt](https://github.com/GregTechCEu/GregTech-Community-Pack/files/12778080/crash-2023-09-28_21.43.37-server.txt)

**Comment by Orzipan** [comment]
I just restored a backup and I successfully removed the valve, only to have the game crash a short time later, maybe cause by trying to insert (from a multi pipe) in to a broken tank?

**Comment by htmlcsjs** [comment]
cannot reproduce, sorry
this is my setup
![image](https://github.com/GregTechCEu/GregTech-Community-Pack/assets/46023024/b13fe1a6-2cc8-4704-bab6-418206957826)

**Comment by htmlcsjs** [comment]
GT Issue, now fixed
