### ISSUE TITLE
[BUG] Server deployment for version 1.7.3

### ISSUE THREAD

**Issue by Infernal15** [GregTechCEu/GregTech-Community-Pack#114]
### Description of the problem:
Currently, the 1.7.3 release uses the 1.6.0 release of the NAE2 module, which has a bug that affects server deployment. The crash report with this bug is attached below.

---- Minecraft Crash Report ----
// Lolis deobfuscated this stacktrace using MCP's stable-39 mappings.
// Don't do that.

Time: 2023-12-17 01:50:06 CET
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Neeve's AE2: Extended Life Additions (nae2)
Caused by: java.lang.NoClassDefFoundError: co/neeve/nae2/client/rendering/models/crafting/DenseCraftingCubeRendering
    at co.neeve.nae2.common.registration.Registration.<init>(Registration.java:42)
    at co.neeve.nae2.NAE2.preInit(NAE2.java:62)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
    at sun.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
    at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:99)
    at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333)
    at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:125)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
    at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: co.neeve.nae2.client.rendering.models.crafting.DenseCraftingCubeRendering
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
    ... 37 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@2e060819 from coremod FMLCorePlugin
    at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:260)
    at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
    ... 39 more
Caused by: java.lang.RuntimeException: Attempted to load class co/neeve/nae2/client/rendering/models/crafting/DenseCraftingCubeRendering for invalid side SERVER
    at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:62)
    at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:256)
    ... 41 more

No Mixin Metadata is found in the Stacktrace.

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Linux (amd64) version 6.1.0-12-amd64
  Java Version: 1.8.0_312, Temurin
  Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Temurin
  Memory: 122947904 bytes (117 MB) / 514301952 bytes (490 MB) up to 31136546816 bytes (29694 MB)
  JVM Flags: 3 total; -Xms128M -XX:MaxRAMPercentage=95.0 -XX:+UseSerialGC
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 LoliASM 5.18 Powered by Forge 14.23.5.2860 74 mods loaded, 74 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID                                   | Version                             | Source                                                      | Signature                                |
       |:----- |:------------------------------------ |:----------------------------------- |:----------------------------------------------------------- |:---------------------------------------- |
       | LCH   | minecraft                            | 1.12.2                              | minecraft.jar                                               | None                                     |
       | LCH   | mcp                                  | 9.42                                | minecraft.jar                                               | None                                     |
       | LCH   | FML                                  | 8.0.99.99                           | forge-1.12.2-14.23.5.2860.jar                               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCH   | forge                                | 14.23.5.2860                        | forge-1.12.2-14.23.5.2860.jar                               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCH   | creativecoredummy                    | 1.0.0                               | minecraft.jar                                               | None                                     |
       | LCH   | gcp                                  | 1.0.0                               | .                                                           | None                                     |
       | LCH   | littletilescore                      | 1.0.0                               | minecraft.jar                                               | None                                     |
       | LCH   | xaerominimap_core                    | 1.12.2-1.0                          | minecraft.jar                                               | None                                     |
       | LCH   | xaeroworldmap_core                   | 1.12.2-1.0                          | minecraft.jar                                               | None                                     |
       | LCH   | mixinbooter                          | 8.8                                 | minecraft.jar                                               | None                                     |
       | LCH   | foamfixcore                          | 7.7.4                               | minecraft.jar                                               | None                                     |
       | LCH   | randompatches                        | 1.12.2-1.22.1.10                    | randompatches-1.12.2-1.22.1.10.jar                          | None                                     |
       | LCH   | configanytime                        | 1.0                                 | !configanytime-1.0.jar                                      | None                                     |
       | LCH   | jei                                  | 4.25.1                              | HadEnoughItems_1.12.2-4.25.1.jar                            | None                                     |
       | LCH   | appleskin                            | 1.0.14                              | AppleSkin-mc1.12-1.0.14.jar                                 | None                                     |
       | LCH   | appliedenergistics2                  | rv6-stable-7-extended_life-v0.55.27 | appliedenergistics2-rv6-stable-7-extended_life-v0.55.27.jar | None                                     |
       | LCH   | badwithernocookiereloaded            | 1.12.2-3.4.18                       | badwithernocookiereloaded-1.12.2-3.4.18.jar                 | None                                     |
       | LCH   | baubles                              | 1.5.2                               | Baubles-1.12-1.5.2.jar                                      | None                                     |
       | LCH   | betterbedrockgen                     | 6.0.2                               | BetterBedrockGenerator-1.12-6.1.1.jar                       | None                                     |
       | LCH   | betterbuilderswands                  | 0.13.2                              | BetterBuildersWands-1.12.2-0.13.2.271+5997513.jar           | None                                     |
       | LCH   | betterquesting                       | 4.1.0                               | BetterQuestingUnofficial-4.1.0.jar                          | None                                     |
       | LCH   | modularui                            | 2.4.0                               | modularui-2.4.0.jar                                         | None                                     |
       | LCH   | bogosorter                           | 1.4.6                               | bogosorter-1.4.6.jar                                        | None                                     |
       | LCH   | buildinggadgets                      | 2.8.4                               | BuildingGadgets-2.8.4.jar                                   | None                                     |
       | LCH   | spark                                | 1.5.2                               | spark-forge1122.jar                                         | None                                     |
       | LCH   | loliasm                              | 5.18                                | censoredasm5.18.jar                                         | None                                     |
       | LCH   | chameleon                            | 1.12-4.1.3                          | Chameleon-1.12-4.1.3.jar                                    | None                                     |
       | LCH   | chatcalculator                       | @VERSION@                           | chatcalculator-1.0.1.jar                                    | None                                     |
       | LCH   | chesttransporter                     | 2.8.8                               | ChestTransporter-1.12.2-2.8.8.jar                           | None                                     |
       | LCH   | chisel                               | MC1.12.2-1.0.2.45                   | Chisel-MC1.12.2-1.0.2.45.jar                                | None                                     |
       | LCH   | codechickenlib                       | 3.2.3.358                           | CodeChickenLib-1.12.2-3.2.3.358-universal.jar               | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCH   | cosmeticarmorreworked                | 1.12.2-v5a                          | CosmeticArmorReworked-1.12.2-v5a.jar                        | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
       | LCH   | craftingtweaks                       | 9.0.1                               | CraftingTweaks_1.12.2-9.0.1.jar                             | None                                     |
       | LCH   | creativecore                         | 1.10.0                              | CreativeCore_v1.10.71_mc1.12.2.jar                          | None                                     |
       | LCH   | elevatorid                           | 1.3.14                              | ElevatorMod-1.12.2-1.3.14.jar                               | None                                     |
       | LCH   | fastfurnace                          | 1.3.1                               | FastFurnace-1.12.2-1.3.1.jar                                | None                                     |
       | LCH   | findme                               | 1.0.0                               | findme-1.12.2-1.0.0.jar                                     | None                                     |
       | LCH   | xporbclump                           | 2.0                                 | Fixeroo-2.0.jar                                             | None                                     |
       | LCH   | ae2fc                                | 2.4.33-r                            | Fluid%20Craft%20for%20AE2-2.4.33-r.jar                      | None                                     |
       | LCH   | foamfix                              | @VERSION@                           | foamfix-0.10.15-1.12.2.jar                                  | None                                     |
       | LCH   | forgelin                             | 1.8.4                               | Forgelin-1.8.4.jar                                          | None                                     |
       | LCH   | storagedrawers                       | 5.5.0                               | StorageDrawers-1.12.2-5.5.0.jar                             | None                                     |
       | LCH   | framedcompactdrawers                 | 1.2.7                               | framedcompactdrawers-1.2.7.jar                              | None                                     |
       | LCH   | ftbbackups                           | 1.1.0.1                             | FTBBackups-1.1.0.1.jar                                      | None                                     |
       | LCH   | ftblib                               | 5.4.7.2                             | FTBLib-5.4.7.2.jar                                          | None                                     |
       | LCH   | ftbutilities                         | 5.4.1.131                           | FTBUtilities-5.4.1.131.jar                                  | None                                     |
       | LCH   | universaltweaks                      | 1.12.2-1.8.0                        | UniversalTweaks-1.12.2-1.8.0.jar                            | None                                     |
       | LCH   | groovyscript                         | 0.7.1                               | groovyscript-0.7.1.jar                                      | None                                     |
       | LCH   | theoneprobe                          | 1.4.28                              | theoneprobe-1.12-1.4.28.jar                                 | None                                     |
       | LCH   | gregtech                             | 2.8.3-beta                          | gregtech-1.12.2-2.8.3-beta.jar                              | None                                     |
       | LCH   | gcym                                 | 1.2.7                               | GregicalityMultiblocks-1.2.7.jar                            | None                                     |
       | LCH   | harvest                              | 1.12-1.2.8-25                       | Harvest-1.12-1.2.8-25.jar                                   | None                                     |
       | LCH   | incontrol                            | 3.9.18                              | incontrol-1.12-3.9.18.jar                                   | None                                     |
       | LCH   | lunatriuscore                        | 1.2.0.42                            | LunatriusCore-1.12.2-1.2.0.42-universal.jar                 | None                                     |
       | LCH   | ingameinfoxml                        | 2.8.2.94                            | InGameInfoXML-1.12.2-2.8.2.94-universal.jar                 | None                                     |
       | LCH   | littletiles                          | 1.5.0                               | LittleTiles_v1.5.85_mc1.12.2.jar                            | None                                     |
       | LCE   | nae2                                 | 1.6.0                               | nae2-1.6.0.jar                                              | None                                     |
       | LC    | naturescompass                       | 1.8.5                               | NaturesCompass-1.12.2-1.8.5.jar                             | None                                     |
       | LC    | netherportalfix                      | 5.3.17                              | NetherPortalFix_1.12.1-5.3.17.jar                           | None                                     |
       | LC    | openglider                           | @VERSION@                           | OpenGlider-1.12.1-1.1.0.jar                                 | None                                     |
       | LC    | placebo                              | 1.6.0                               | Placebo-1.12.2-1.6.1.jar                                    | None                                     |
       | LC    | randomtweaks                         | 1.12.2-2.8.3.1                      | randomtweaks-1.12.2-2.8.3.1.jar                             | 20d08fb3fe9c268a63a75d337fb507464c8aaccd |
       | LC    | sledgehammer                         | 1.12.2-2.0.25                       | Sledgehammer-1.12.2-2.0.25-thin.jar                         | 565fa4dbf20e7c3c4423950ca8e0bdabf7568796 |
       | LC    | tombmanygraves                       | 1.12-4.2.0                          | TombManyGraves-1.12-4.2.0.jar                               | None                                     |
       | LC    | tombmanygraves2api                   | 1.12.2-1.0.0                        | tombmanygraves2api-1.12.2-1.0.0.jar                         | None                                     |
       | LC    | tombmanypluginscosmeticarmorreworked | 1.0.0                               | tombmanypluginscosmeticarmorreworked-1.0.0.jar              | None                                     |
       | LC    | topaddons                            | 1.12.2-1.13.0                       | topaddons-1.12.2-1.13.0.jar                                 | None                                     |
       | LC    | topextras                            | 1.0.1                               | topextras-1.12.2-1.0.1.jar                                  | None                                     |
       | LC    | torchmaster                          | 1.8.5.0                             | torchmaster_1.12.2-1.8.5.0.jar                              | None                                     |
       | LC    | visualores                           | 0.2.4                               | visualores-0.2.4.jar                                        | None                                     |
       | LC    | xaerominimap                         | 23.9.1                              | Xaeros_Minimap_23.9.1_Forge_1.12.jar                        | None                                     |
       | LC    | xaeroworldmap                        | 1.37.1                              | XaerosWorldMap_1.37.1_Forge_1.12.jar                        | None                                     |
       | LC    | xtones                               | 1.2.2                               | Xtones-1.2.2.jar                                            | None                                     |
       | LC    | phosphor-lighting                    | 1.12.2-0.2.9.3                      | phosphor-1.12.2-0.2.9.3-SNAPSHOT.jar                        | None                                     |
  Loaded coremods (and transformers): RandomPatches (randompatches-1.12.2-1.22.1.10.jar)
                                        com.therandomlabs.randompatches.core.RPTransformer
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.15-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      FluidCraftCore (Fluid%20Craft%20for%20AE2-2.4.33-r.jar)
                                        com.glodblock.github.coremod.FCClassTransformer
                                      ForgelinPlugin (Forgelin-1.8.4.jar)
                                        
                                      Fixeroo (Fixeroo-2.0.jar)
                                        
                                      CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      PhosphorFMLPlugin (phosphor-1.12.2-0.2.9.3-SNAPSHOT.jar)
                                        
                                      GregTechLoadingPlugin (gregtech-1.12.2-2.8.3-beta.jar)
                                        gregtech.asm.GregTechTransformer
                                      UniversalTweaksCore (UniversalTweaks-1.12.2-1.8.0.jar)
                                        
                                      BogoSorter-Core (bogosorter-1.4.6.jar)
                                        
                                      XaeroMinimapPlugin (Xaeros_Minimap_23.9.1_Forge_1.12.jar)
                                        xaero.common.core.transformer.ChunkTransformer
                                        xaero.common.core.transformer.NetHandlerPlayClientTransformer
                                        xaero.common.core.transformer.EntityPlayerTransformer
                                        xaero.common.core.transformer.AbstractClientPlayerTransformer
                                        xaero.common.core.transformer.WorldClientTransformer
                                        xaero.common.core.transformer.EntityPlayerMPTransformer
                                        xaero.common.core.transformer.EntityPlayerSPTransformer
                                        xaero.common.core.transformer.PlayerListTransformer
                                        xaero.common.core.transformer.SaveFormatTransformer
                                        xaero.common.core.transformer.GuiIngameForgeTransformer
                                        xaero.common.core.transformer.MinecraftServerTransformer
                                        xaero.common.core.transformer.GuiBossOverlayTransformer
                                        xaero.common.core.transformer.ModelRendererTransformer
                                      ModularUI-Core (modularui-2.4.0.jar)
                                        com.cleanroommc.modularui.core.ClassTransformer
                                      CreativePatchingLoader (CreativeCore_v1.10.71_mc1.12.2.jar)
                                        
                                      GroovyScript-Core (groovyscript-0.7.1.jar)
                                        
                                      LittlePatchingLoader (LittleTiles_v1.5.85_mc1.12.2.jar)
                                        com.creativemd.littletiles.LittleTilesTransformer
                                      LoliASM (censoredasm5.18.jar)
                                        
                                      AE2ELCore (appliedenergistics2-rv6-stable-7-extended_life-v0.55.27.jar)
                                        appeng.core.transformer.AE2ELTransformer
                                      ConfigAnytimePlugin (!configanytime-1.0.jar)
                                        
                                      MixinBooter (!mixinbooter-8.8.jar)
                                        
                                      VOEarlyMixinLoader (visualores-0.2.4.jar)
                                        
                                      NAE2-Core (nae2-1.6.0.jar)
                                        
                                      XaeroWorldMapPlugin (XaerosWorldMap_1.37.1_Forge_1.12.jar)
                                        xaero.map.core.transformer.ChunkTransformer
                                        xaero.map.core.transformer.NetHandlerPlayClientTransformer
                                        xaero.map.core.transformer.EntityPlayerTransformer
                                        xaero.map.core.transformer.AbstractClientPlayerTransformer
                                        xaero.map.core.transformer.WorldClientTransformer
                                        xaero.map.core.transformer.EntityPlayerMPTransformer
                                        xaero.map.core.transformer.PlayerListTransformer
                                        xaero.map.core.transformer.SaveFormatTransformer
                                        xaero.map.core.transformer.BiomeColorHelperTransformer
                                        xaero.map.core.transformer.MinecraftServerTransformer
                                        xaero.map.core.transformer.MinecraftTransformer
  AE2 Version: stable rv6-stable-7-extended_life-v0.55.27 for Forge 14.23.5.2847
  Suspected Mods: Neeve's AE2: Extended Life Additions (nae2), Forge Mod Loader (FML), Minecraft Forge (forge)
  Profiler Position: N/A (disabled)
  Is Modded: Definitely; Server brand changed to 'fml,forge'
  Type: Dedicated Server (map_server.txt)
  
  
###   Suggestion for solving the problem:
To solve this problem, you only need to update the NAE2 module to version 1.6.1.

**Comment by htmlcsjs** [comment]
will be by in #115
