### ISSUE TITLE
Embeddium Collision with Oculus leads to crash on use of shaders

### ISSUE THREAD

**Issue by Tetahydril** [GregTechCEu/GregTech-Community-Pack#123]
The game seems to reproducibly crash when it has to render a specific entity using the Bliss Shaderpack because of the same error:

java.lang.NullPointerException: Cannot invoke "me.jellysquid.mods.sodium.client.render.chunk.RenderSection.getCulledBlockEntities()" because "renderSection" is null
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderBlockEntities(SodiumWorldRenderer.java:388) ~[embeddium-0.3.19+mc1.20.1-all.jar%23345!/:?] 

I beleive this happens because the game has to render a specific entity referencing a specific function, but it is using the wrong package (net.irisshaders.iris.layer.OuterWrappedRenderType.wrapExactlyOnce instead of net.coderbot.iris.layer.OuterWrappedRenderType.wrapExactlyOnce)

**TerrafirmaGreg Version:**
1.20.x-0.7.12

**Operating System:**
Win 10

**GPU:**
Nvidia RTX 4080 Super

**Java Version:**
java 8 update 321

**Shader:**
Bliss v2.0.4

[crash-2024-07-19_22.10.27-client.txt](https://github.com/user-attachments/files/16405167/crash-2024-07-19_22.10.27-client.txt)
[crash-2024-07-26_10.59.21-client.txt](https://github.com/user-attachments/files/16405168/crash-2024-07-26_10.59.21-client.txt)
[crash-2024-07-28_18.42.11-client.txt](https://github.com/user-attachments/files/16405169/crash-2024-07-28_18.42.11-client.txt)
[crash-2024-07-28_18.55.16-client.txt](https://github.com/user-attachments/files/16405170/crash-2024-07-28_18.55.16-client.txt)
[crash-2024-07-28_19.08.59-client.txt](https://github.com/user-attachments/files/16405171/crash-2024-07-28_19.08.59-client.txt)

**Comment by htmlcsjs** [comment]
i dont know what modpack your playing there, but you may be looking for https://github.com/GregTechCEu/GregTech-Modern-Community-Pack if your playing on 1.20
