### ISSUE TITLE
请问任务书汉化有吗？

### ISSUE THREAD

**Issue by KLZW-10086** [GregTechCEu/GregTech-Community-Pack#42]
想试试这个整合包，请问去哪里下载任务书汉化

**Comment by CrossElectronics** [comment]
No there is not. You need to do it yourself or rely on the community. Also, please use English on a public repository so that the author and others can understand and potentially help you :)
没有，需要自己汉化或者依靠社区。此外，在公共仓库请尽量使用英语，这样仓库的作者和社区玩家才能理解与帮助你 :)
