### ISSUE TITLE
saramium

### ISSUE THREAD

**Issue by epicgamerjamer** [GregTechCEu/GregTech-Community-Pack#86]
![image](https://github.com/GregTechCEu/GregTech-Community-Pack/assets/101027811/becd3f72-72a9-4e8d-ba91-2277ffead116)
![image](https://github.com/GregTechCEu/GregTech-Community-Pack/assets/101027811/27ba7911-2aec-4e9a-a72b-d1055807c03a)

**Comment by Anthonity** [comment]
what
