### ISSUE TITLE
groovyscript causing server to crash on startup

### ISSUE THREAD

**Issue by ramenwizard** [GregTechCEu/GregTech-Community-Pack#94]
after going through all the mods i found that the server would launch fine with groovyscript removed, but crashed when it was re-added.
[crash-2023-07-18_08.53.01-server.txt](https://github.com/GregTechCEu/GregTech-Community-Pack/files/12083267/crash-2023-07-18_08.53.01-server.txt)

**Comment by htmlcsjs** [comment]
Fixed in 28431a8
