### ISSUE TITLE
Fluix plate localization

### ISSUE THREAD

**Issue by pyure** [GregTechCEu/GregTech-Community-Pack#97]
**Problem**
Fluix plate needs name
![image](https://github.com/GregTechCEu/GregTech-Community-Pack/assets/8617528/cc543a11-c827-4f09-b029-126dc09b1d10)

So do Fluix gems (all types), dust and blocks.  Probably everything-fluix.  (I think its just the material string "Fluix" itself which needs localizing maybe)

**Versions**
**pack** -1.7.0
**GT** gregtech-1.12.2-2.7.2-beta

**Comment by htmlcsjs** [comment]
tech didnt update the Lang for materials for 2.7 :trollface:

**Comment by joendter** [comment]
This should be fixed in 1.7.1
